curl -X POST http://localhost:7718/add/Four
curl -X POST http://localhost:7718/add/score
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/seven
curl -X POST http://localhost:7718/add/years
curl -X POST http://localhost:7718/add/ago
curl -X POST http://localhost:7718/add/our
curl -X POST http://localhost:7718/add/fathers
curl -X POST http://localhost:7718/add/brought
curl -X POST http://localhost:7718/add/forth
curl -X POST http://localhost:7718/add/on
curl -X POST http://localhost:7718/add/this
curl -X POST http://localhost:7718/add/continent
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/new
curl -X POST http://localhost:7718/add/nation
curl -X POST http://localhost:7718/add/conceived
curl -X POST http://localhost:7718/add/in
curl -X POST http://localhost:7718/add/Liberty
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/dedicated
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/proposition
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/all
curl -X POST http://localhost:7718/add/men
curl -X POST http://localhost:7718/add/are
curl -X POST http://localhost:7718/add/created
curl -X POST http://localhost:7718/add/equal
curl -X POST http://localhost:7718/add/Now
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/are
curl -X POST http://localhost:7718/add/engaged
curl -X POST http://localhost:7718/add/in
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/great
curl -X POST http://localhost:7718/add/civil
curl -X POST http://localhost:7718/add/war
curl -X POST http://localhost:7718/add/testing
curl -X POST http://localhost:7718/add/whether
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/nation
curl -X POST http://localhost:7718/add/or
curl -X POST http://localhost:7718/add/any
curl -X POST http://localhost:7718/add/nation
curl -X POST http://localhost:7718/add/so
curl -X POST http://localhost:7718/add/conceived
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/so
curl -X POST http://localhost:7718/add/dedicated
curl -X POST http://localhost:7718/add/can
curl -X POST http://localhost:7718/add/long
curl -X POST http://localhost:7718/add/endure
curl -X POST http://localhost:7718/add/We
curl -X POST http://localhost:7718/add/are
curl -X POST http://localhost:7718/add/met
curl -X POST http://localhost:7718/add/on
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/great
curl -X POST http://localhost:7718/add/battlefield
curl -X POST http://localhost:7718/add/of
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/war
curl -X POST http://localhost:7718/add/We
curl -X POST http://localhost:7718/add/have
curl -X POST http://localhost:7718/add/come
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/dedicate
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/portion
curl -X POST http://localhost:7718/add/of
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/field
curl -X POST http://localhost:7718/add/as
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/final
curl -X POST http://localhost:7718/add/resting
curl -X POST http://localhost:7718/add/place
curl -X POST http://localhost:7718/add/for
curl -X POST http://localhost:7718/add/those
curl -X POST http://localhost:7718/add/who
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/gave
curl -X POST http://localhost:7718/add/their
curl -X POST http://localhost:7718/add/lives
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/nation
curl -X POST http://localhost:7718/add/might
curl -X POST http://localhost:7718/add/live
curl -X POST http://localhost:7718/add/It
curl -X POST http://localhost:7718/add/is
curl -X POST http://localhost:7718/add/altogether
curl -X POST http://localhost:7718/add/fitting
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/proper
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/should
curl -X POST http://localhost:7718/add/do
curl -X POST http://localhost:7718/add/this
curl -X POST http://localhost:7718/add/But
curl -X POST http://localhost:7718/add/in
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/larger
curl -X POST http://localhost:7718/add/sense
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/can
curl -X POST http://localhost:7718/add/not
curl -X POST http://localhost:7718/add/dedicate
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/can
curl -X POST http://localhost:7718/add/not
curl -X POST http://localhost:7718/add/consecrate
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/can
curl -X POST http://localhost:7718/add/not
curl -X POST http://localhost:7718/add/hallow
curl -X POST http://localhost:7718/add/this
curl -X POST http://localhost:7718/add/ground
curl -X POST http://localhost:7718/add/The
curl -X POST http://localhost:7718/add/brave
curl -X POST http://localhost:7718/add/men
curl -X POST http://localhost:7718/add/living
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/dead
curl -X POST http://localhost:7718/add/who
curl -X POST http://localhost:7718/add/struggled
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/have
curl -X POST http://localhost:7718/add/consecrated
curl -X POST http://localhost:7718/add/it
curl -X POST http://localhost:7718/add/far
curl -X POST http://localhost:7718/add/above
curl -X POST http://localhost:7718/add/our
curl -X POST http://localhost:7718/add/poor
curl -X POST http://localhost:7718/add/power
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/add
curl -X POST http://localhost:7718/add/or
curl -X POST http://localhost:7718/add/detract
curl -X POST http://localhost:7718/add/The
curl -X POST http://localhost:7718/add/world
curl -X POST http://localhost:7718/add/will
curl -X POST http://localhost:7718/add/little
curl -X POST http://localhost:7718/add/note
curl -X POST http://localhost:7718/add/nor
curl -X POST http://localhost:7718/add/long
curl -X POST http://localhost:7718/add/remember
curl -X POST http://localhost:7718/add/what
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/say
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/but
curl -X POST http://localhost:7718/add/it
curl -X POST http://localhost:7718/add/can
curl -X POST http://localhost:7718/add/never
curl -X POST http://localhost:7718/add/forget
curl -X POST http://localhost:7718/add/what
curl -X POST http://localhost:7718/add/they
curl -X POST http://localhost:7718/add/did
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/It
curl -X POST http://localhost:7718/add/is
curl -X POST http://localhost:7718/add/for
curl -X POST http://localhost:7718/add/us
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/living
curl -X POST http://localhost:7718/add/rather
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/be
curl -X POST http://localhost:7718/add/dedicated
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/unfinished
curl -X POST http://localhost:7718/add/work
curl -X POST http://localhost:7718/add/which
curl -X POST http://localhost:7718/add/they
curl -X POST http://localhost:7718/add/who
curl -X POST http://localhost:7718/add/fought
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/have
curl -X POST http://localhost:7718/add/thus
curl -X POST http://localhost:7718/add/far
curl -X POST http://localhost:7718/add/so
curl -X POST http://localhost:7718/add/nobly
curl -X POST http://localhost:7718/add/advanced
curl -X POST http://localhost:7718/add/It
curl -X POST http://localhost:7718/add/is
curl -X POST http://localhost:7718/add/rather
curl -X POST http://localhost:7718/add/for
curl -X POST http://localhost:7718/add/us
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/be
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/dedicated
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/great
curl -X POST http://localhost:7718/add/task
curl -X POST http://localhost:7718/add/remaining
curl -X POST http://localhost:7718/add/before
curl -X POST http://localhost:7718/add/us
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/from
curl -X POST http://localhost:7718/add/these
curl -X POST http://localhost:7718/add/honored
curl -X POST http://localhost:7718/add/dead
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/take
curl -X POST http://localhost:7718/add/increased
curl -X POST http://localhost:7718/add/devotion
curl -X POST http://localhost:7718/add/to
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/cause
curl -X POST http://localhost:7718/add/for
curl -X POST http://localhost:7718/add/which
curl -X POST http://localhost:7718/add/they
curl -X POST http://localhost:7718/add/gave
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/last
curl -X POST http://localhost:7718/add/full
curl -X POST http://localhost:7718/add/measure
curl -X POST http://localhost:7718/add/of
curl -X POST http://localhost:7718/add/devotion
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/we
curl -X POST http://localhost:7718/add/here
curl -X POST http://localhost:7718/add/highly
curl -X POST http://localhost:7718/add/resolve
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/these
curl -X POST http://localhost:7718/add/dead
curl -X POST http://localhost:7718/add/shall
curl -X POST http://localhost:7718/add/not
curl -X POST http://localhost:7718/add/have
curl -X POST http://localhost:7718/add/died
curl -X POST http://localhost:7718/add/in
curl -X POST http://localhost:7718/add/vain
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/this
curl -X POST http://localhost:7718/add/nation
curl -X POST http://localhost:7718/add/under
curl -X POST http://localhost:7718/add/God
curl -X POST http://localhost:7718/add/shall
curl -X POST http://localhost:7718/add/have
curl -X POST http://localhost:7718/add/a
curl -X POST http://localhost:7718/add/new
curl -X POST http://localhost:7718/add/birth
curl -X POST http://localhost:7718/add/of
curl -X POST http://localhost:7718/add/freedom
curl -X POST http://localhost:7718/add/and
curl -X POST http://localhost:7718/add/that
curl -X POST http://localhost:7718/add/government
curl -X POST http://localhost:7718/add/of
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/people
curl -X POST http://localhost:7718/add/by
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/people
curl -X POST http://localhost:7718/add/for
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/people
curl -X POST http://localhost:7718/add/shall
curl -X POST http://localhost:7718/add/not
curl -X POST http://localhost:7718/add/perish
curl -X POST http://localhost:7718/add/from
curl -X POST http://localhost:7718/add/the
curl -X POST http://localhost:7718/add/earth